version: '3.1'

services:
  app:
    build: .
    image: "reunion-fastapi-app:0.1"
    ports:
      - 8000:8000
    restart: "always"
    volumes:
        - .:/.project_reunion/
    environment:
      - PGDATA=/var/lib/postgresql/
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_reunion
      - DB_HOST=db
    entrypoint: ["/.project_reunion/start_server.sh"]
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_reunion
    ports:
      - "5432:5432"

volumes:
  postgres_data:


networks:
  app:
    driver: bridge
